#!/bin/sh
youtube-dl \
    -x \
    --write-thumbnail  \
    --audio-format mp3 \
    --add-metadata \
    --metadata-from-title '%(artist)s - %(title)s' \
    -o '%(title)s.%(ext)s' \
    "$@" 

magick mogrify -fuzz 20% -trim +repage -shave 7x7 -resize 500x500^ -format jpg *.webp
for file in *.mp3; do ffmpeg -hide_banner -loglevel error -i "$file" -i *.jpg -map 0:a -map 1 -c:a flac -id3v2_version 3 -disposition:1 attached_pic -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (front)" "${file%.mp3}.flac"; done && rm *.mp3 *.jpg *.webp
