#!/bin/sh
ffmpeg \
    -video_size 1920x1080 \
    -framerate 60 \
    -f x11grab \
    -i :0.0 \
    -c:v libx264 \
    -pix_fmt yuv420p \
    -crf 0 \
    -preset ultrafast \
    -y \
    output.mp4
